spring:
  application:
    name: gemini-langchain-demo

langchain4j:
  open-ai:
    chat-model:
      api-key: xxxx
      model-name: Qwen/Qwen2.5-7B-Instruct
      base-url: https://api.siliconflow.cn
  google-ai-gemini:
    chat-model:
      api-key: xxxx
      model-name: gemini-2.0-flash

logging:
  level:
    com:
      ai:
        langchain: DEBUG
    dev:
      langchain4j: DEBUG